# Generated by Django 4.2.6 on 2023-10-31 12:29

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='review_code',
            field=models.CharField(default=shop.models.generate_review_code, editable=False, max_length=8, unique=True),
        ),
    ]
