# Generated by Django 4.2.6 on 2023-11-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_purchase_review_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="genshin_uid",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
